@Tmb.OrderManagementSystem.Api_HostAddress = http://localhost:32768

POST {{Tmb.OrderManagementSystem.Api_HostAddress}}/orders
Accept: application/json

{
  "Customer":"teste",
  "Product":"xpto",
  "Price": 1.00
}
###
